music/urls.py
from django.urls import path

from . import views

app_name = "music"
urlpatterns = [
    # 登录注册
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout, name="logout"),

    path('', views.index, name='index'),
    # /music/album_
    path('detail/<int:album_id>/', views.detail, name="detail"),
    path('personal/', views.personal, name='personal'),
    path("my_comments/", views.my_comments, name="my_comments"),
    path("my_collect/", views.my_collect, name="my_collect"),
    path("my_rate/", views.my_rate, name="my_rate"),
    # word song
    path("word_song/<str:word>/", views.word_song, name="word_song"),
    path("learned/<str:song_name>/", views.learned, name="learned"),
    path("unlearned/<str:song_name>/", views.unlearned, name="unlearned"),
    path("have_learned", views.have_learned, name="have_learned"),
    path("have_unlearned", views.have_unlearned, name="have_unlearned"),
    path("have_listened", views.have_listened, name="have_listened"),

    # /music/add
    # url(r"^create_album/$", views.Creatalbum, name="index"),
    # /music/2/add_song
    # url(r"^(?P<album_id>[0-9]+)/add_song/$", views.Add_Song, name="add_song"),
    # /music/2/delete_song/3
    # url(r"delete_song/(?P<song_id>[0-9]+)$", views.Delete_song, name="song-delete"),
    # /music/2/delete
    # url(r"^(?P<album_id>[0-9]+)/delete_album/$", views.Delete, name="album-delete"),
    # music/albumid/favorite_album/
    path(
        "<int:album_id>/favorite_album/",
        views.favorite_album,
        name="favorite_album",
    ),
    # music/song_id/favorite_song/
    path(
        "<int:song_id>/favorite_song/",
        views.favorite_song,
        name="favorite_song", )
]

music_py/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'music_py.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^music/', include('music.urls')),
    url(r"^", include("music.urls")),
    url(r"^admin/", admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
import random

from django.db import models
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField


class AutoCreatedField(models.DateTimeField):
    """
    A DateTimeField that automatically populates itself at
    object creation.

    By default, sets editable=False, default=datetime.now.

    """

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('editable', False)
        kwargs.setdefault('default', now)
        super(AutoCreatedField, self).__init__(*args, **kwargs)


class AutoLastModifiedField(AutoCreatedField):
    """
    A DateTimeField that updates itself on each save() of the model.

    By default, sets editable=False and default=datetime.now.

    """

    def pre_save(self, model_instance, add):
        value = now()
        setattr(model_instance, self.attname, value)
        return value


class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-updating
    ``created`` and ``modified`` fields.

    """
    created = AutoCreatedField(_('created'))
    modified = AutoLastModifiedField(_('modified'))

    # 不能以此类直接建立表
    class Meta:
        abstract = True


class User(TimeStampedModel):
    username = models.CharField(max_length=255, unique=True, verbose_name="账号")
    password = models.CharField(max_length=255, verbose_name="密码")
    phone = PhoneNumberField(null=False, blank=False, unique=True)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name_plural = "用户"

class Album(TimeStampedModel):
    # user = models.ForeignKey(User, default=1, on_delete=True)
    # is_favorite = models.BooleanField(default=False)
    # artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100, default='英语')
    album_logo = models.FileField()

    def __str__(self):
        return self.album_title + " - " + self.genre

    class Meta:
        verbose_name_plural = "专辑"

class Word(TimeStampedModel):
    content = models.CharField(max_length=32, verbose_name='单词内容')

    def __str__(self):
        return self.content
    class Meta:
        verbose_name_plural = "单词"


class Song(TimeStampedModel):
    album = models.ForeignKey(Album, on_delete=models.CASCADE, verbose_name='音频专辑')
    name = models.CharField(max_length=250, verbose_name='名字')
    author = models.CharField(verbose_name='作者', max_length=128)
    audio_file = models.URLField(null=False)
    content = models.TextField(verbose_name='音频内容')
    word = models.ManyToManyField(Word, verbose_name='单词')
    created = models.DateTimeField(auto_now=True)
    size = models.FloatField(verbose_name='文件大小')
    view_num = models.IntegerField(default=0, verbose_name='播放数')
    translation = models.TextField(verbose_name='翻译内容')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "音频"

    # def on
    def delete(self, using=None, keep_parents=False):
        file = Song.objects.filter(audio_file=self.audio_file)
        file.delete()
        super(Song, self).delete()

    def save(self, *args, **kwargs):
        # 第一次添加单词时会更新释义
        if self._state.adding is True:
            word_content = self.content

        super(Song, self).save(*args, **kwargs)


class UserSong(TimeStampedModel):
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    song = models.ForeignKey(Song, verbose_name='歌曲', on_delete=models.CASCADE)
    finished = models.SmallIntegerField(verbose_name='当前状态')

    class Meta:
        verbose_name_plural = "用户音频"


def gen_newcode():
    length = 5
    strs = 'abcdefghijk_mnopqrstuvwxyz'
    new_code = ''.join(random.choices(strs, k=length))
    code = RegisterCode.objects.filter(code=new_code).first()
    while code is not None:
        new_code = ''.join(random.choices(strs, k=length))
        code = RegisterCode.objects.filter(code=new_code).first()
    return code


class RegisterCode(TimeStampedModel):
    # 注册码
    code = models.CharField(primary_key=True, default=gen_newcode, max_length=10)

    class Meta:
        verbose_name_plural = "注册码"


class UserWord(TimeStampedModel):
    word = models.ForeignKey(Word, on_delete=models.CASCADE, verbose_name='单词')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')
    learned = models.BooleanField(verbose_name='是否掌握')

    def __str__(self):
        return self.user.username + ':' + self.word.content + '是否掌握:' + str(self.learned)

    class Meta:
        verbose_name_plural = "用户单词"


class MessageBoard(TimeStampedModel):
    title = models.CharField(max_length=32, verbose_name='公告标题')
    content = models.TextField(verbose_name='公告内容')

    def __str__(self):
        return self.content

    class Meta:
        verbose_name_plural = "公告板"

music/views.py
# encoding=utf-8
from functools import wraps

from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.urls import reverse

from music.models import *
from .forms import RegisterForm, LoginForm, SongForm, AlbumForm

AUDIO_FILE_TYPES = ["wav", "mp3", "ogg"]
IMAGE_FILE_TYPES = ["png", "jpg", "jpeg"]
app_name = "music"


def login_in(func):  # 验证用户是否登录
    @wraps(func)
    def wrapper(*args, **kwargs):
        request = args[0]
        is_login = request.session.get("login_in")
        if is_login:
            return func(*args, **kwargs)
        else:
            return redirect(reverse("login"))

    return wrapper


# 登录功能
def login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            # phone = form.cleaned_data["phone"]
            user = User.objects.filter(username=username).first()
            if user and user.password == password:
                request.session["login_in"] = True
                request.session["user_id"] = user.id
                request.session["name"] = username
                # 用户第一次注册，让他选标签
                # new = request.session.get('new')
                # if new:
                #     tags = Tags.objects.all()
                #     return render(request, 'music/choose_tag.html', {'tags': tags})
                return redirect(reverse("music:index"))
            else:
                return render(
                    request, "music/login.html", {"form": form, "message": "账户或密码错误"}
                )
        else:

            print('form invalid')
    else:
        form = LoginForm()
        print('here')
        return render(request, "music/login.html", {"form": form})


# 注册功能
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        error = None
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password2"]
            phone = form.cleaned_data['phone']
            User.objects.create(username=username, password=password, phone=phone)
            request.session['new'] = 'true'
            # 根据表单数据创建一个新的用户
            return redirect(reverse("music:login"))  # 跳转到登录界面
        else:
            return render(
                request, "music/register.html", {"form": form, "error": error}
            )  # 表单验证失败返回一个空表单到注册页面
    form = RegisterForm()
    return render(request, "music/register.html", {"form": form})


def logout(request):
    if not request.session.get("login_in", None):  # 不在登录状态跳转回首页
        return redirect(reverse("index"))
    request.session.flush()  # 清除session信息
    return redirect(reverse("index"))


def recommend_songs(user_id=None, n=5):
    if user_id is None:
        songs = Song.objects.order_by('?')[:n]
    else:
        # 未掌握的单词
        unlearned_word = UserWord.objects.filter(user_id=user_id, learned=False)
        songs = Song.objects.filter(word__in=unlearned_word).order_by('?')
        learned_songs = UserSong.objects.filter(user_id=user_id)
        learned_songs = [learned_song.song for learned_song in learned_songs]
        if len(songs) < n:
            songs.extend(Song.objects.all() - learned_songs[:n - len(learned_songs)])
    return set(songs)


def index(request):
    # try:
    # if not request.music.is_authenticated:
    #     return render(request, "music/login.html")
    # else:
    albums = Album.objects.all()
    songs = recommend_songs()
    # query = request.GET.get("q")

    # if query:
    #     albums = albums.filter(
    #         Q(album_title__icontains=query) | Q(artist__icontains=query)
    #     ).distinct()
    #
    message_board = MessageBoard.objects.order_by('-modified').first()
    #     song_results = song_results.filter(Q(song_title__contains=query)).distinct()
    return render(
        request,
        "music/index.html",
        {"all_albums": albums, 'songs': songs, 'message_board': message_board},
    )
    # return render(request, "music/index.html", {"all_albums": albums})


# except Exception as e:
#     return render(request, 'music/httperror.html')


def detail(request, album_id):
    album = Album.objects.get(id=album_id)
    return render(request, 'music/detail.html', {'album': album})


def random_choice_songs():
    return Song.objects.order_by('?')[:5]


# add_song
def Add_Song(request, album_id):
    # 未登录
    if not request.music.is_authenticated:
        return render(request, "music/login.html")
    else:
        # 是否提交表单
        song_form = SongForm(request.POST or None, request.FILES or None)
        album = get_object_or_404(Album, pk=album_id)
        if song_form.is_valid():
            album_songs = album.song_set.all()

            # 判断歌曲是否存在
            for s in album_songs:
                if s.song_title == song_form.cleaned_data.get("name"):
                    context = {
                        "album": album,
                        "form": song_form,
                        "error": "you have already have this song",
                    }
                    return render(request, "music/add_song.html", context)

            song = song_form.save(commit=False)
            song.audio_file = request.FILES["audio_file"]
            a = request.FILES["audio_file"]
            a = str(a)
            song.album = album
            file_type = a.split(".")[-1]
            file_name = a.split(".")[0]
            song.song_title = file_name
            file_type = file_type.lower()
            # 格式不支持
            if file_type not in AUDIO_FILE_TYPES:
                context = {
                    "all_albums": album,
                    "form": song_form,
                    "error": "your song is not supported",
                }
                return render(request, "music/add_song.html", context)
            song.save()
            return render(request, "music/detail.html", {"album": album})

        else:
            context = {"form": song_form, "album": album}
            return render(request, "music/add_song.html", context)


# create album
def Creatalbum(request):
    # 未登录
    if not request.music.is_authenticated:
        return render(request, "music/login.html")
    else:
        album_form = AlbumForm(request.POST or None, request.FILES or None)
        if album_form.is_valid():
            album = album_form.save(commit=False)
            album.music = request.music
            album.album_logo = request.FILES["album_logo"]

            file_type = album.album_logo.url.split(".")[-1]
            file_type = file_type.lower()

            # 格式不对
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    "albums": album,
                    "form": album_form,
                    "error": "file type is not supported",
                }
                return render(request, "music/album_form.html", context)
            print("here is right")
            album.save()
            all_albums = Album.objects.filter(music=request.music)
            return render(request, "music/index.html", {"all_albums": all_albums})
        #
        else:
            # 处理从 details 页面发来的请求 返回到创建界面
            context = {"form": album_form}
            return render(request, "music/album_form.html", context)


# Delete
def Delete(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    album.delete()
    all_albums = Album.objects.filter(music=request.music)
    return render(request, "music/index.html", {"all_albums": all_albums})


def Delete_song(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    song.delete()
    album = song.album
    return render(request, "music/detail.html", {"album": album})


# register


def favorite_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)

    try:
        if album.is_favorite:
            album.is_favorite = False
        else:
            album.is_favorite = True

        album.save()
    except (KeyError, Album.DoesNotExist):
        return JsonResponse({"success": False})
    all_album = Album.objects.filter(music=request.music)
    return render(request, "music/index.html", {"all_albums": all_album})


# favorite song
def favorite_song(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    album = song.album
    try:
        if song.is_favorite:
            song.is_favorite = False
        else:
            song.is_favorite = True

        song.save()
    except (KeyError, Song.DoesNotExist):
        return JsonResponse({"error": "song is not exist"})
    return render(request, "music/detail.html", {"album": album})


@login_in
def personal(request):
    user_id = request.session.get('user_id')
    user = User.objects.get(id=user_id)
    return render(request, 'music/personal.html', {"user": user})


@login_in
def have_learned(request):
    user_id = request.session.get('user_id')
    user_learned_song = UserSong.objects.filter(user_id=user_id, finished=True)
    learned_words = set()
    for user_song in user_learned_song:
        song_words = user_song.song.word.all()
        for word in song_words:
            word, _ = UserWord.objects.get_or_create(word=word, user_id=user_id, defaults={'learned': True})
            if not word.learned:
                word.learned = True
                word.save()
            learned_words.add(word.word)
    return render(request, 'music/word_list.html', {"learned_words": learned_words, 'title': '已掌握单词'})


@login_in
def have_unlearned(request):
    user_id = request.session.get('user_id')
    user_learned_song = UserSong.objects.filter(user_id=user_id, finished=False)
    unlearned_words = set()
    for user_song in user_learned_song:
        song_words = user_song.song.word.all()

music/templates/music/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'music/css/style.css' %}">
    {#    <link rel="stylesheet" type="text/css" href="{% static 'music/css/bootstrap.min.css' %}">#}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
          crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
          crossorigin="anonymous">
    {% block css %}
    {% endblock %}
</head>
<body background="{% static 'music/images/background.png' %}">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        {#        header#}
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">English learning</a>
        </div>
        {#            items#}
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">

                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
                {#生成图标#}
                <li class="">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; music
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:index' %}">

                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>

                <button type="submit" class="btn btn-default">搜索</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if request.session.login_in == True %}
                    <li><a href='#' id="have_listened"></a></li>
                    <li><a href="{% url 'music:have_learned' %}">已掌握的单词</a></li>
                    <li><a href="{% url 'music:have_unlearned' %}">未掌握的单词</a></li>
                    <li><a href="{% url 'music:personal' %}">{{ request.session.name }}</a></li>
                    <li class="nav navbar-nav navbar-right">
                        <a href="{% url 'music:logout' %}">
                            <span class="glyphicon glyphicon-off"></span>&nbsp; 登出
                        </a>
                    </li>
                    {#                    <li><a href="{% url 'clear_cache' %}">清除缓存</a></li>#}
                {% else %}
                    <li class="active">
                        <a href="{% url 'music:login' %}">
                            <span class="glyphicon glyphicon-plus"></span> 登录
                        </a>
                    </li>
                    <li class="nav navbar-nav navbar-right">
                        <a href="{% url 'music:register' %}">
                            <span class="glyphicon glyphicon-off"></span>&nbsp; 注册
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% if message %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div id="myAlert" class="alert alert-success">
                <a href="#" class="close" data-dismiss="alert">&times;</a><strong>{{ message }}</strong></div>
        </div>
    </div>
{% endif %}
{% block  body %}

{% endblock %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/cplayer/dist/cplayer.min.js"></script>

{#<script src="{% static 'music/js/bootstrap.min.js' %}"></script>#}


<script>
    $.get('/have_listened', function (data, status) {
        var listened=document.getElementById('have_listened');
        listened.text='已播放: '+data.listened_count;
    }).fail(function () {
        console.log('登录后可见');
    })
</script>

{% block script %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block body %}
    {% if album %}
        <div class="container-fluid song-container">
            <div class="row">
                {#left album info#}
                <div class="col-sm-4 col-md-3">
                    <div class="panel panel-default">
                        <div class="panel panel-body">
                            <a href="{% url 'music:index' %}"></a>
                            <img src=" {{ album.album_logo }}" class="img-responsive">
                            <h1>{{ album.album_title }}</h1>
                            <h2>{{ album.artist }}</h2>
                        </div>

                    </div>
                </div>

                {#         right information    一行一行的显示#}
                <div class="col-sm-8 col-md-9">
                    {#                    <ul class="nav nav-pills" style="margin-bottom: 10px">#}
                    {#                        <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">view All </a>#}
                    {#                        </li>#}
                    {#                        <li role="presentation" class="active"><a href="{% url 'music:add_song' album.id %}">add#}
                    {#                            Song </a>#}
                    {#                        </li>#}
                    {#                    </ul>#}

                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h3>所有音频</h3>
                            {% if error_message %}
                                <p><strong>  {{ error_message }}  </strong></p>
                            {% endif %}
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>名字</th>
                                    <th>作者</th>
                                    <th>播放数</th>
                                    <th>关键词</th>
                                    <th>播放</th>
                                </tr>

                                </thead>
                                <tbody>

                                {% for song in album.song_set.all %}
                                    <tr>
                                        <td>{{ song.name }}</td>
                                        <td>{{ song.author }}</td>
                                        <td>{{ song.view_num }}</td>
                                        <td> {% for word in song.word.all %}
                                            <a href="{% url 'music:word_song' word.content %}"> {{ word.content }}  </a>
                                        {% endfor %}
                                        </td>
                                        <td>
                                            <a href="#">
                                                <button type="button" class="btn btn-success btn-xs" id="{{ forloop.counter0 }}" onclick="play_songs(this)">
                                                    <span class="glyphicon glyphicon-play"></span>
                                                    &nbsp; 播放
                                                </button>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div id="music" hidden></div>

                </div>
            </div>
        </div>
    {% else %}
        <h2 align="center"> album does not exist!</h2>
        <h4 align="center"><a href="{% url 'music:index' %}">back to index view</a></h4>

    {% endif %}
{% endblock %}

{% block script %}
    <script>
        const options = {
            zoomOutKana: true,
            big: true,
            size: 200,
            shadowDom: false
        };
        let player = new cplayer({
                element: document.getElementById('music'),
                playlist: [
                    {% for song in album.song_set.all %}
                        {
                            src: "{{ song.audio_file }}",
                            poster: '',
                            name: '{{ song.name }}',
                            artist: '{{ song.author }}',
                            lyric: '{{ song.contents }}',
                            content: "{{ song.content }}",
                            sublyric: '{{ song.translation }}'
                        },
                    {% endfor %}
                ],
                dropDownMenuMode: 'bottom',
                volume: 0.75,
                width: '100%',
                showPlaylistButton: true,
                size: '20px',
                {#autoplay:true,#}
            }
        );
        function play_songs(object) {
            var app=document.getElementById('music');
            app.removeAttribute('hidden');
            player.to(object.id);
            player.play();
        }
    </script>
    {#     显示文本内容#}
    {#    <script>#}
    {#        var show = 1;#}
    {#        function toggle_content() {#}
    {#            var x = document.getElementById('song_content');#}
    {#            var a = player.nowplay;#}
    {#            x.innerHTML = "<p>" + a.content + "</p>";#}
    {#            $('#song_content').animate({opacity: show});#}
    {#            show = !show;#}
    {##}
    {#        }#}
    {#    </script>#}
{% endblock %}

music/templates/music/personal.html
{% extends 'music/base.html' %}
{% load grav_tag %}
{% block body %}
    <div class="warp-content">
        <div class="container-fluid">
            <h1 align="center" style="margin-bottom: 20px">个人信息</h1>
            <div class="thumbnail movie">
                <div class="row" style="margin-top: 20px">
                    <div class="col-md-9 col-md-offset-1">
                        <div class="row">
                            <div class="col-md-4 col-sm-12">
                                <img CLASS="img-responsive img-rounded" src='{{ user.email|gravatar:"150" }}'>
                            </div>
                            <div class="col-md-8 col-sm-12">
                                <div class="row">
                                    <p style="padding: 10px;margin-left: 5px;font-size: 20px">
                                        用户名: {{ user.username }}
                                    </p>
                                </div>
                                <div class="row">
                                    <p style="padding: 10px;margin-left: 5px;font-size: 20px">
                                        邮箱: {{ user.email }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="margin-top: 20px">
                            <div class="col-md-4">
                                <h2><a style="padding: 10px; font-size: 30px" class="btn-lg btn-block btn-warning" href="{% url 'music:my_collect' %}">我的收藏</a>
                                </h2>
                            </div>
                            <div class="col-md-4">
                                <h2><a style="padding: 10px; font-size: 30px" class="btn-lg btn-block btn-info" href="{% url 'music:my_comments' %}">我的评论</a>
                                </h2>
                            </div>
                            <div class="col-md-4">
                                <h2><a style="padding: 10px; font-size: 30px" class="btn-lg btn-block btn-primary " href="{% url 'music:my_rate' %}">我的评分</a>
                                </h2>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row" style="margin-top: 20px">
                    <div class="col-md-9 col-md-offset-1">
                        <form action="{% url 'music:personal' %}" method='post' autocomplete="on">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.label_tag }}
                                    {{ field.errors }}
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <div class="row">
                                <div class="col-md-6">
                                    <button type="reset" class="btn-lg btn-block btn-danger ">重置</button>
                                </div>
                                <div class="col-md-6">
                                    <button type="submit" class="btn-lg btn-success btn-block">修改信息</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}